name: Auto-Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  clone:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Pyinstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Compile py-compiler.py
      run: |
        python -3 pyinstaller -F py-compiler.py
        git commit -a -m "Compile py-compiler"
        git push    
    - name: Create Release
      run: |
          echo "done!"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest Compile"
        files: |
          dist/py-compiler.exe
